// <auto-generated />
using System;
using Main.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Main.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116213101_CreateTickets")]
    partial class CreateTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Main.Models.Accreditation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Team_Member_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Valid_From")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Valid_To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Team_Member_Id");

                    b.ToTable("Accreditations");
                });

            modelBuilder.Entity("Main.Models.ActivationZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Partner_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Required_Power")
                        .HasColumnType("int");

                    b.Property<int>("Zone_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Partner_Id");

                    b.HasIndex("Zone_Id");

                    b.ToTable("ActivationZones");
                });

            modelBuilder.Entity("Main.Models.LogisticItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Zone_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Zone_Id");

                    b.ToTable("LogisticItems");
                });

            modelBuilder.Entity("Main.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Arrives_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hand_Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transport")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Main.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("Main.Models.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Ends_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Participant_Id")
                        .HasColumnType("int");

                    b.Property<int>("Stage_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Starts_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Participant_Id");

                    b.HasIndex("Stage_Id");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("Main.Models.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("Main.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Participant_Id")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Participant_Id");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Main.Models.TechnicalBreak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Ends_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stage_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Starts_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Stage_Id");

                    b.ToTable("TechnicalBreaks");
                });

            modelBuilder.Entity("Main.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Buyer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Entrance_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Qr_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Main.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("Main.Models.VolunteerShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Ends_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Starts_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Volunteer_Id")
                        .HasColumnType("int");

                    b.Property<int>("Zone_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Volunteer_Id");

                    b.HasIndex("Zone_Id");

                    b.ToTable("VolunteersShifts");
                });

            modelBuilder.Entity("Main.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Main.Models.Accreditation", b =>
                {
                    b.HasOne("Main.Models.TeamMember", "Team_Member")
                        .WithMany("Accreditations")
                        .HasForeignKey("Team_Member_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team_Member");
                });

            modelBuilder.Entity("Main.Models.ActivationZone", b =>
                {
                    b.HasOne("Main.Models.Partner", "Partner")
                        .WithMany("ActivationZones")
                        .HasForeignKey("Partner_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Models.Zone", "Zone")
                        .WithMany("Activation_Zones")
                        .HasForeignKey("Zone_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Main.Models.LogisticItem", b =>
                {
                    b.HasOne("Main.Models.Zone", "Zone")
                        .WithMany("Logistic_Items")
                        .HasForeignKey("Zone_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Main.Models.Performance", b =>
                {
                    b.HasOne("Main.Models.Participant", "Participant")
                        .WithMany("Performances")
                        .HasForeignKey("Participant_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Models.Stage", "Stage")
                        .WithMany("Performances")
                        .HasForeignKey("Stage_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Main.Models.TeamMember", b =>
                {
                    b.HasOne("Main.Models.Participant", "Participant")
                        .WithMany("Team_Members")
                        .HasForeignKey("Participant_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Main.Models.TechnicalBreak", b =>
                {
                    b.HasOne("Main.Models.Stage", "Stage")
                        .WithMany("TechnicalBreaks")
                        .HasForeignKey("Stage_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Main.Models.VolunteerShift", b =>
                {
                    b.HasOne("Main.Models.Volunteer", "Volunteer")
                        .WithMany("Volunteer_Shifts")
                        .HasForeignKey("Volunteer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Models.Zone", "Zone")
                        .WithMany("Volunteer_Shifts")
                        .HasForeignKey("Zone_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Volunteer");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Main.Models.Participant", b =>
                {
                    b.Navigation("Performances");

                    b.Navigation("Team_Members");
                });

            modelBuilder.Entity("Main.Models.Partner", b =>
                {
                    b.Navigation("ActivationZones");
                });

            modelBuilder.Entity("Main.Models.Stage", b =>
                {
                    b.Navigation("Performances");

                    b.Navigation("TechnicalBreaks");
                });

            modelBuilder.Entity("Main.Models.TeamMember", b =>
                {
                    b.Navigation("Accreditations");
                });

            modelBuilder.Entity("Main.Models.Volunteer", b =>
                {
                    b.Navigation("Volunteer_Shifts");
                });

            modelBuilder.Entity("Main.Models.Zone", b =>
                {
                    b.Navigation("Activation_Zones");

                    b.Navigation("Logistic_Items");

                    b.Navigation("Volunteer_Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
