// <auto-generated />
using System;
using Main.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Main.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116204952_CreatePerformances")]
    partial class CreatePerformances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Main.Models.Accreditation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Team_Member_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Valid_From")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Valid_To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Team_Member_Id");

                    b.ToTable("Accreditations");
                });

            modelBuilder.Entity("Main.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Arrives_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hand_Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transport")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Main.Models.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Ends_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Participant_Id")
                        .HasColumnType("int");

                    b.Property<int>("Stage_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Starts_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Participant_Id");

                    b.HasIndex("Stage_Id");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("Main.Models.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("Main.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Participant_Id")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Participant_Id");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Main.Models.Accreditation", b =>
                {
                    b.HasOne("Main.Models.TeamMember", "Team_Member")
                        .WithMany("Accreditations")
                        .HasForeignKey("Team_Member_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team_Member");
                });

            modelBuilder.Entity("Main.Models.Performance", b =>
                {
                    b.HasOne("Main.Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("Participant_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Models.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("Stage_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Main.Models.TeamMember", b =>
                {
                    b.HasOne("Main.Models.Participant", "Participant")
                        .WithMany("Team_Members")
                        .HasForeignKey("Participant_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Main.Models.Participant", b =>
                {
                    b.Navigation("Team_Members");
                });

            modelBuilder.Entity("Main.Models.TeamMember", b =>
                {
                    b.Navigation("Accreditations");
                });
#pragma warning restore 612, 618
        }
    }
}
