// <auto-generated />
using System;
using Main.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Main.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116234617_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Main.Models.Accreditation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Team_Member_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Valid_From")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Valid_To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Team_Member_Id");

                    b.ToTable("Accreditations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Team_Member_Id = 1,
                            Valid_From = new DateTime(2024, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid_To = new DateTime(2024, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Team_Member_Id = 2,
                            Valid_From = new DateTime(2024, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid_To = new DateTime(2024, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Team_Member_Id = 3,
                            Valid_From = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid_To = new DateTime(2024, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Team_Member_Id = 4,
                            Valid_From = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid_To = new DateTime(2024, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Team_Member_Id = 5,
                            Valid_From = new DateTime(2024, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valid_To = new DateTime(2024, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Main.Models.ActivationZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Partner_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Required_Power")
                        .HasColumnType("int");

                    b.Property<int>("Zone_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Partner_Id");

                    b.HasIndex("Zone_Id");

                    b.ToTable("ActivationZones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Notes = "Setup live broadcast point",
                            Partner_Id = 1,
                            Required_Power = 500,
                            Zone_Id = 2
                        },
                        new
                        {
                            Id = 2,
                            Notes = "Food stalls area",
                            Partner_Id = 2,
                            Required_Power = 200,
                            Zone_Id = 3
                        });
                });

            modelBuilder.Entity("Main.Models.DailyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DailyReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contents = "The festival kicked off with SuperCoolBand delivering an electrifying performance on the Main Stage. Attendance was high, and the crowd was enthusiastic. Minor incidents included a lost ticket at the entrance, which was resolved quickly.",
                            Date = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Successful opening day with great performances."
                        },
                        new
                        {
                            Id = 2,
                            Contents = "JazzMasters captivated the audience at the Jazz Corner with their soulful tunes. The atmosphere was relaxed and enjoyable. A medical emergency was handled efficiently by the on-site team, ensuring the safety of all attendees.",
                            Date = new DateTime(2024, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Second day focused on jazz with smooth performances."
                        });
                });

            modelBuilder.Entity("Main.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Happened_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ticket_Id")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zone_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ticket_Id");

                    b.HasIndex("Zone_Id");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lost ticket",
                            Happened_At = new DateTime(2024, 7, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Ticket_Id = 1,
                            Zone_Id = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Medical emergency",
                            Happened_At = new DateTime(2024, 7, 11, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Ticket_Id = 2,
                            Zone_Id = 3
                        });
                });

            modelBuilder.Entity("Main.Models.LogisticItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Zone_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Zone_Id");

                    b.ToTable("LogisticItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Speaker System",
                            Quantity = 10,
                            Zone_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lighting Rig",
                            Quantity = 5,
                            Zone_Id = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Barricades",
                            Quantity = 50,
                            Zone_Id = 2
                        });
                });

            modelBuilder.Entity("Main.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Arrives_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hand_Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transport")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Participants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Arrives_At = new DateTime(2024, 7, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Contact_Number = "555-1234",
                            Hand_Color = "Red",
                            Name = "SuperCoolBand",
                            Notes = "Requires soundcheck at 3 PM"
                        },
                        new
                        {
                            Id = 2,
                            Arrives_At = new DateTime(2024, 7, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Contact_Number = "555-5678",
                            Hand_Color = "Blue",
                            Name = "JazzMasters",
                            Notes = "Bringing their own equipment"
                        });
                });

            modelBuilder.Entity("Main.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact_Number = "555-2222",
                            Name = "City Radio"
                        },
                        new
                        {
                            Id = 2,
                            Contact_Number = "555-3333",
                            Name = "Local Eats"
                        });
                });

            modelBuilder.Entity("Main.Models.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Ends_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Participant_Id")
                        .HasColumnType("int");

                    b.Property<int>("Stage_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Starts_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Participant_Id");

                    b.HasIndex("Stage_Id");

                    b.ToTable("Performances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ends_At = new DateTime(2024, 7, 10, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Participant_Id = 1,
                            Stage_Id = 1,
                            Starts_At = new DateTime(2024, 7, 10, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Ends_At = new DateTime(2024, 7, 11, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            Participant_Id = 2,
                            Stage_Id = 2,
                            Starts_At = new DateTime(2024, 7, 11, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Main.Models.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 5000,
                            Location = "Central Park",
                            Name = "Main Stage"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1500,
                            Location = "Downtown Plaza",
                            Name = "Jazz Corner"
                        });
                });

            modelBuilder.Entity("Main.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Participant_Id")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Participant_Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact_Number = "555-4128",
                            Name = "Alice",
                            Participant_Id = 1,
                            Role = "Vocalist"
                        },
                        new
                        {
                            Id = 2,
                            Contact_Number = "555-4312",
                            Name = "Bob",
                            Participant_Id = 1,
                            Role = "Guitarist"
                        },
                        new
                        {
                            Id = 3,
                            Contact_Number = "555-9412",
                            Name = "Charlie",
                            Participant_Id = 2,
                            Role = "Saxophonist"
                        },
                        new
                        {
                            Id = 4,
                            Contact_Number = "555-9481",
                            Name = "Diana",
                            Participant_Id = 2,
                            Role = "Drummer"
                        },
                        new
                        {
                            Id = 5,
                            Contact_Number = "555-4144",
                            Name = "Eve",
                            Participant_Id = 1,
                            Role = "Drummer"
                        });
                });

            modelBuilder.Entity("Main.Models.TechnicalBreak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Ends_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stage_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Starts_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Stage_Id");

                    b.ToTable("TechnicalBreaks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ends_At = new DateTime(2024, 7, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Stage_Id = 1,
                            Starts_At = new DateTime(2024, 7, 10, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Main.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Buyer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Entrance_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Qr_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Buyer_Name = "John Doe",
                            Contact_Number = "555-6666",
                            Qr_Code = "TICKET12345",
                            Status = "Unused",
                            Type = "VIP"
                        },
                        new
                        {
                            Id = 2,
                            Buyer_Name = "Jane Smith",
                            Contact_Number = "555-7777",
                            Qr_Code = "TICKET67890",
                            Status = "Unused",
                            Type = "General"
                        },
                        new
                        {
                            Id = 3,
                            Buyer_Name = "Mike Johnson",
                            Contact_Number = "555-8888",
                            Qr_Code = "TICKET54321",
                            Status = "Unused",
                            Type = "General"
                        });
                });

            modelBuilder.Entity("Main.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact_Number = "555-7777",
                            Name = "Frank",
                            Role = "Stage helper"
                        },
                        new
                        {
                            Id = 2,
                            Contact_Number = "555-8888",
                            Name = "Grace",
                            Role = "Crowd control"
                        });
                });

            modelBuilder.Entity("Main.Models.VolunteerShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Ends_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Starts_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Volunteer_Id")
                        .HasColumnType("int");

                    b.Property<int>("Zone_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Volunteer_Id");

                    b.HasIndex("Zone_Id");

                    b.ToTable("VolunteersShifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ends_At = new DateTime(2024, 7, 10, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Starts_At = new DateTime(2024, 7, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Volunteer_Id = 1,
                            Zone_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Ends_At = new DateTime(2024, 7, 11, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Starts_At = new DateTime(2024, 7, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Volunteer_Id = 2,
                            Zone_Id = 2
                        });
                });

            modelBuilder.Entity("Main.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Behind Main Stage",
                            Name = "Backstage",
                            Type = "Restricted"
                        },
                        new
                        {
                            Id = 2,
                            Location = "North Gate",
                            Name = "Entrance",
                            Type = "Public"
                        },
                        new
                        {
                            Id = 3,
                            Location = "East Side",
                            Name = "Food Court",
                            Type = "Public"
                        });
                });

            modelBuilder.Entity("Main.Models.Accreditation", b =>
                {
                    b.HasOne("Main.Models.TeamMember", "Team_Member")
                        .WithMany("Accreditations")
                        .HasForeignKey("Team_Member_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team_Member");
                });

            modelBuilder.Entity("Main.Models.ActivationZone", b =>
                {
                    b.HasOne("Main.Models.Partner", "Partner")
                        .WithMany("ActivationZones")
                        .HasForeignKey("Partner_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Models.Zone", "Zone")
                        .WithMany("Activation_Zones")
                        .HasForeignKey("Zone_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Main.Models.Incident", b =>
                {
                    b.HasOne("Main.Models.Ticket", "Ticket")
                        .WithMany("Incidents")
                        .HasForeignKey("Ticket_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Models.Zone", "Zone")
                        .WithMany("Incidents")
                        .HasForeignKey("Zone_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Main.Models.LogisticItem", b =>
                {
                    b.HasOne("Main.Models.Zone", "Zone")
                        .WithMany("Logistic_Items")
                        .HasForeignKey("Zone_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Main.Models.Performance", b =>
                {
                    b.HasOne("Main.Models.Participant", "Participant")
                        .WithMany("Performances")
                        .HasForeignKey("Participant_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Models.Stage", "Stage")
                        .WithMany("Performances")
                        .HasForeignKey("Stage_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Main.Models.TeamMember", b =>
                {
                    b.HasOne("Main.Models.Participant", "Participant")
                        .WithMany("Team_Members")
                        .HasForeignKey("Participant_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Main.Models.TechnicalBreak", b =>
                {
                    b.HasOne("Main.Models.Stage", "Stage")
                        .WithMany("TechnicalBreaks")
                        .HasForeignKey("Stage_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Main.Models.VolunteerShift", b =>
                {
                    b.HasOne("Main.Models.Volunteer", "Volunteer")
                        .WithMany("Volunteer_Shifts")
                        .HasForeignKey("Volunteer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Models.Zone", "Zone")
                        .WithMany("Volunteer_Shifts")
                        .HasForeignKey("Zone_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Volunteer");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Main.Models.Participant", b =>
                {
                    b.Navigation("Performances");

                    b.Navigation("Team_Members");
                });

            modelBuilder.Entity("Main.Models.Partner", b =>
                {
                    b.Navigation("ActivationZones");
                });

            modelBuilder.Entity("Main.Models.Stage", b =>
                {
                    b.Navigation("Performances");

                    b.Navigation("TechnicalBreaks");
                });

            modelBuilder.Entity("Main.Models.TeamMember", b =>
                {
                    b.Navigation("Accreditations");
                });

            modelBuilder.Entity("Main.Models.Ticket", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Main.Models.Volunteer", b =>
                {
                    b.Navigation("Volunteer_Shifts");
                });

            modelBuilder.Entity("Main.Models.Zone", b =>
                {
                    b.Navigation("Activation_Zones");

                    b.Navigation("Incidents");

                    b.Navigation("Logistic_Items");

                    b.Navigation("Volunteer_Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
