// <auto-generated />
using System;
using Main.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Main.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Main.Models.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Administrators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "054-5417",
                            Name = "Bohdan"
                        });
                });

            modelBuilder.Entity("Main.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdministratorId = 1,
                            Date = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An electrifying rock music festival featuring top bands from around the world.",
                            Name = "Summer Rock Festival"
                        },
                        new
                        {
                            Id = 2,
                            AdministratorId = 1,
                            Date = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A cozy jazz event to warm up your winter nights with smooth tunes.",
                            Name = "Winter Jazz Nights"
                        });
                });

            modelBuilder.Entity("Main.Models.EventBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZoneActivationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("ZoneActivationId");

                    b.ToTable("EventBlocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndsAt = new DateTime(2024, 8, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rock Band Performance",
                            StartsAt = new DateTime(2024, 8, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1,
                            Type = "Performance",
                            ZoneActivationId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndsAt = new DateTime(2024, 8, 15, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Intermission",
                            StartsAt = new DateTime(2024, 8, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Break",
                            ZoneActivationId = 1
                        },
                        new
                        {
                            Id = 3,
                            EndsAt = new DateTime(2024, 8, 15, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Closing Act",
                            StartsAt = new DateTime(2024, 8, 15, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1,
                            Type = "Performance",
                            ZoneActivationId = 1
                        },
                        new
                        {
                            Id = 4,
                            EndsAt = new DateTime(2024, 12, 5, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jazz Evening",
                            StartsAt = new DateTime(2024, 12, 5, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2,
                            Type = "Performance",
                            ZoneActivationId = 4
                        },
                        new
                        {
                            Id = 5,
                            EndsAt = new DateTime(2024, 12, 5, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Intermission",
                            StartsAt = new DateTime(2024, 12, 5, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Break",
                            ZoneActivationId = 4
                        },
                        new
                        {
                            Id = 6,
                            EndsAt = new DateTime(2024, 12, 5, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Late Night Jazz",
                            StartsAt = new DateTime(2024, 12, 5, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 3,
                            Type = "Performance",
                            ZoneActivationId = 4
                        });
                });

            modelBuilder.Entity("Main.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HappenedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lost sunglasses during the event.",
                            HappenedAt = new DateTime(2024, 8, 15, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            IsResolved = true,
                            TicketId = 1,
                            Type = "Lost Item"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Attendee fainted and required medical attention.",
                            HappenedAt = new DateTime(2024, 12, 5, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            IsResolved = true,
                            TicketId = 4,
                            Type = "Medical Emergency"
                        },
                        new
                        {
                            Id = 3,
                            Description = "QR code not scanning at entry.",
                            HappenedAt = new DateTime(2024, 8, 15, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            IsResolved = false,
                            TicketId = 6,
                            Type = "Ticket Issue"
                        });
                });

            modelBuilder.Entity("Main.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "054-7001",
                            Description = "Leading provider of sound equipment for events.",
                            Name = "SoundWave Co."
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "054-7002",
                            Description = "Specialists in event security and crowd management.",
                            Name = "EventSecure Ltd."
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "054-7003",
                            Description = "Catering services for large-scale events.",
                            Name = "Foodies Inc."
                        });
                });

            modelBuilder.Entity("Main.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArrivesAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transport")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivesAt = new DateTime(2024, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactNumber = "054-5441",
                            HandColor = "Red",
                            Name = "The Rockers",
                            Notes = "Requires backstage access.",
                            Transport = "Bus"
                        },
                        new
                        {
                            Id = 2,
                            ArrivesAt = new DateTime(2024, 12, 4, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactNumber = "054-5499",
                            HandColor = "Blue",
                            Name = "Jazz Masters",
                            Notes = "Needs special sound equipment.",
                            Transport = "Van"
                        },
                        new
                        {
                            Id = 3,
                            ArrivesAt = new DateTime(2024, 12, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactNumber = "054-5490",
                            HandColor = "Green",
                            Name = "Fire Jazz",
                            Notes = "Bringing their own instruments.",
                            Transport = "Car"
                        });
                });

            modelBuilder.Entity("Main.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Role = "Guitarist",
                            TeamId = 1,
                            TicketId = 1
                        },
                        new
                        {
                            Id = 2,
                            Role = "Drummer",
                            TeamId = 1,
                            TicketId = 2
                        },
                        new
                        {
                            Id = 3,
                            Role = "Saxophonist",
                            TeamId = 2,
                            TicketId = 3
                        },
                        new
                        {
                            Id = 4,
                            Role = "Vocalist",
                            TeamId = 2,
                            TicketId = 4
                        },
                        new
                        {
                            Id = 5,
                            Role = "Vocalist",
                            TeamId = 3,
                            TicketId = 5
                        });
                });

            modelBuilder.Entity("Main.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuyerContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyerContactNumber = "054-5001",
                            BuyerName = "Alice Johnson",
                            EventId = 1,
                            QrCode = "QR123456"
                        },
                        new
                        {
                            Id = 2,
                            BuyerContactNumber = "054-5002",
                            BuyerName = "Bob Smith",
                            EventId = 1,
                            QrCode = "QR123457"
                        },
                        new
                        {
                            Id = 3,
                            BuyerContactNumber = "054-6001",
                            BuyerName = "Charlie Brown",
                            EventId = 2,
                            QrCode = "QR223456"
                        },
                        new
                        {
                            Id = 4,
                            BuyerContactNumber = "054-6002",
                            BuyerName = "Diana Prince",
                            EventId = 2,
                            QrCode = "QR223457"
                        },
                        new
                        {
                            Id = 5,
                            BuyerContactNumber = "054-6003",
                            BuyerName = "Ethan Hunt",
                            EventId = 2,
                            QrCode = "QR223458"
                        },
                        new
                        {
                            Id = 6,
                            BuyerContactNumber = "054-5003",
                            BuyerName = "Fiona Glenanne",
                            EventId = 1,
                            QrCode = "QR123458"
                        },
                        new
                        {
                            Id = 7,
                            BuyerContactNumber = "054-5004",
                            BuyerName = "George Clooney",
                            EventId = 1,
                            QrCode = "QR123459"
                        });
                });

            modelBuilder.Entity("Main.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "054-8001",
                            Name = "John Doe",
                            Role = "Sound Technician",
                            Salary = 12000
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "054-8002",
                            Name = "Jane Smith",
                            Role = "Security Staff",
                            Salary = 10000
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "054-8003",
                            Name = "Mike Johnson",
                            Role = "Catering Staff",
                            Salary = 9000
                        });
                });

            modelBuilder.Entity("Main.Models.WorkerShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneActivationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.HasIndex("ZoneActivationId");

                    b.ToTable("WorkerShifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndsAt = new DateTime(2024, 8, 15, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartsAt = new DateTime(2024, 8, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1,
                            ZoneActivationId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndsAt = new DateTime(2024, 8, 15, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartsAt = new DateTime(2024, 8, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2,
                            ZoneActivationId = 2
                        },
                        new
                        {
                            Id = 3,
                            EndsAt = new DateTime(2024, 8, 15, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StartsAt = new DateTime(2024, 8, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3,
                            ZoneActivationId = 3
                        },
                        new
                        {
                            Id = 4,
                            EndsAt = new DateTime(2024, 12, 5, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartsAt = new DateTime(2024, 12, 5, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 1,
                            ZoneActivationId = 4
                        },
                        new
                        {
                            Id = 5,
                            EndsAt = new DateTime(2024, 12, 5, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartsAt = new DateTime(2024, 12, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 2,
                            ZoneActivationId = 5
                        },
                        new
                        {
                            Id = 6,
                            EndsAt = new DateTime(2024, 12, 5, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StartsAt = new DateTime(2024, 12, 5, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerId = 3,
                            ZoneActivationId = 6
                        });
                });

            modelBuilder.Entity("Main.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Central Area",
                            Name = "Main Stage",
                            Type = "Performance"
                        },
                        new
                        {
                            Id = 2,
                            Location = "North Wing",
                            Name = "VIP Lounge",
                            Type = "Exclusive"
                        },
                        new
                        {
                            Id = 3,
                            Location = "East Side",
                            Name = "Food Court",
                            Type = "Catering"
                        });
                });

            modelBuilder.Entity("Main.Models.ZoneActivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ZoneActivations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            Notes = "Setup sound systems and lighting.",
                            PartnerId = 1,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            EventId = 1,
                            Notes = "Manage VIP access and security.",
                            PartnerId = 2,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 3,
                            EventId = 1,
                            Notes = "Arrange food stalls and seating.",
                            PartnerId = 3,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 4,
                            EventId = 2,
                            Notes = "Setup sound systems and lighting.",
                            PartnerId = 1,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 5,
                            EventId = 2,
                            Notes = "Manage VIP access and security.",
                            PartnerId = 2,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 6,
                            EventId = 2,
                            Notes = "Arrange food stalls and seating.",
                            PartnerId = 3,
                            ZoneId = 3
                        });
                });

            modelBuilder.Entity("Main.Models.Event", b =>
                {
                    b.HasOne("Main.Models.Administrator", "Administrator")
                        .WithMany("Events")
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("Main.Models.EventBlock", b =>
                {
                    b.HasOne("Main.Models.Team", "Team")
                        .WithMany("EventBlocks")
                        .HasForeignKey("TeamId");

                    b.HasOne("Main.Models.ZoneActivation", "ZoneActivation")
                        .WithMany("EventBlocks")
                        .HasForeignKey("ZoneActivationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("ZoneActivation");
                });

            modelBuilder.Entity("Main.Models.Incident", b =>
                {
                    b.HasOne("Main.Models.Ticket", "Ticket")
                        .WithMany("Incidents")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Main.Models.TeamMember", b =>
                {
                    b.HasOne("Main.Models.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Models.Ticket", "Ticket")
                        .WithOne("TeamMember")
                        .HasForeignKey("Main.Models.TeamMember", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Main.Models.Ticket", b =>
                {
                    b.HasOne("Main.Models.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Main.Models.WorkerShift", b =>
                {
                    b.HasOne("Main.Models.Worker", "Worker")
                        .WithMany("WorkerShifts")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Models.ZoneActivation", "ZoneActivation")
                        .WithMany("WorkerShifts")
                        .HasForeignKey("ZoneActivationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");

                    b.Navigation("ZoneActivation");
                });

            modelBuilder.Entity("Main.Models.ZoneActivation", b =>
                {
                    b.HasOne("Main.Models.Event", "Event")
                        .WithMany("ZoneActivations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Models.Partner", "Partner")
                        .WithMany("ZoneActivations")
                        .HasForeignKey("PartnerId");

                    b.HasOne("Main.Models.Zone", "Zone")
                        .WithMany("ZoneActivations")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Partner");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Main.Models.Administrator", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Main.Models.Event", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("ZoneActivations");
                });

            modelBuilder.Entity("Main.Models.Partner", b =>
                {
                    b.Navigation("ZoneActivations");
                });

            modelBuilder.Entity("Main.Models.Team", b =>
                {
                    b.Navigation("EventBlocks");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("Main.Models.Ticket", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("Main.Models.Worker", b =>
                {
                    b.Navigation("WorkerShifts");
                });

            modelBuilder.Entity("Main.Models.Zone", b =>
                {
                    b.Navigation("ZoneActivations");
                });

            modelBuilder.Entity("Main.Models.ZoneActivation", b =>
                {
                    b.Navigation("EventBlocks");

                    b.Navigation("WorkerShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
